In [1]:
import pandas as pd
complaints = pd.read_csv("complaints.csv")
customers = pd.read_csv("customers_with_login.csv")
transactions = pd.read_csv("transactions.csv")
accounts = pd.read_csv("accounts.csv")

C:\Users\kanyi\AppData\Local\Temp\ipykernel_44872\2531123068.py:4: DtypeWarning: Columns (0: amount, 1: salary_detected) have mixed types. Specify dtype option on import or set low_memory=False.
  transactions = pd.read_csv("transactions.csv")

In [2]:
accounts.head()

,account_id,customer_id,account_number,account_type,currency,current_balance,opened_date
0,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,2970940785,savings,NGN,348724.26,2025-06-20
1,b1b43b1a-5cae-4871-a42a-7797cf814cfc,1721dbca-76cc-4f90-9f8e-46d7f0957162,3957668565,solo,NGN,85809.60,2025-07-27
2,7a339065-4b4a-44bf-b861-b4afa2cf0221,1721dbca-76cc-4f90-9f8e-46d7f0957162,5799321432,current,NGN,6628841.01,2025-01-16
3,b67a9931-8c4e-45cb-882f-c0f8279f109f,e8b21ee1-64be-481d-b191-0fcaf47976d0,9778706452,savings,NGN,517369.64,2026-02-16
4,53cd5643-0a9e-442c-b6ea-87800a5e9c38,e8b21ee1-64be-481d-b191-0fcaf47976d0,6564506237,solo,NGN,172124.46,2026-01-12

In [3]:
customers.info()

<class 'pandas.DataFrame'>
RangeIndex: 3001 entries, 0 to 3000
Data columns (total 19 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   customer_id        3001 non-null   str
 1   first_name         3001 non-null   str
 2   last_name          3001 non-null   str
 3   full_name          3001 non-null   str
 4   gender             3001 non-null   str
 5   age                3001 non-null   int64
 6   date_of_birth      3001 non-null   str
 7   bvn                3001 non-null   int64
 8   nin                3001 non-null   int64
 9   phone_number       3001 non-null   float64
 10  telco_provider     3001 non-null   str
 11  email              3001 non-null   str
 12  state_of_origin    3001 non-null   str
 13  residential_state  3001 non-null   str
 14  banking_branch     3001 non-null   str
 15  solo_candidate     3001 non-null   bool
 16  onboarding_date    3001 non-null   str
 17  username           3001 non-null   str
 18  password           3001 non-null   str
dtypes: bool(1), float64(1), int64(3), str(14)
memory usage: 425.1 KB

In [4]:
transactions.columns

Index(['transaction_id', 'transaction_reference_number', 'account_id',
       'customer_id', 'channel', 'device_id', 'counterparty_bank', 'narration',
       'transaction_type', 'amount', 'currency', 'transaction_balance',
       'transaction_status', 'failure_reason', 'is_fraud_score',
       'fraud_explainability_trace', 'merchant_category', 'merchant_name',
       'salary_detected', 'Loan_signal_score', 'recommended_product',
       'transaction_timestamp'],
      dtype='str')

In [5]:
transactions['amount']

0         15300.71
1          5924.62
2          9261.83
3         40318.61
4         40504.51
            ...
216013    52915.09
216014      mobile
216015      mobile
216016      mobile
216017         NaN
Name: amount, Length: 216018, dtype: object

In [6]:
customer_ids = customers["customer_id"]
legit_complaints = complaints[complaints["customer_id"].isin(customer_ids)]

In [7]:
legit_complaints

,complaint_id,customer_id,account_id,linked_transaction_id,linked_reference,department_code,department_name,priority_level,sentiment,complaint_channel,assigned_agent_id,complaint_timestamp,resolution_timestamp,resolution_time_hours,sla_hours_limit,sla_breach_flag,complaint_status,fraud_related,complaint_text
0,CMP-000001,1721dbca-76cc-4f90-9f8e-46d7f0957162,fa0065d6-188a-41f6-992b-0f9ad10d2e62,2cd76ff1-fad3-4840-bf75-cdfff1e91bdc,TXN550683510360,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A2,2025-08-24 07:42:31,2025-08-26 05:42:31,46.0,48.0,0.0,resolved,0,My transfer of ₦15204.51 with reference TXN550...
1,CMP-000002,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,6e420c2a-9f4c-4e3a-bba2-6950d66bc3ef,TXN682399898141,COC,Card Operations Center,High,calm,call_center,COC_A2,2025-10-04 01:29:08,2025-10-07 23:29:08,94.0,48.0,1.0,open,0,Kindly assist. The ATM transaction of ₦59396.0...
2,CMP-000003,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4d10db2d-f649-4c1a-b098-7ce1735cc4e5,TXN913375010250,COC,Card Operations Center,High,calm,mobile_app,COC_A2,2025-11-04 21:27:41,2025-11-08 05:27:41,80.0,48.0,1.0,escalated,0,Kindly assist. The ATM transaction of ₦49170.0...
3,CMP-000004,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4baabee9-6397-4a62-a1ae-f273da7a1391,TXN309153098109,FRM,Fraud Risk Management,Critical,angry,mobile_app,FRM_A3,2025-10-31 23:29:19,2025-11-01 14:29:19,15.0,24.0,0.0,escalated,1,This is unacceptable. I noticed an unauthorize...
4,CMP-000005,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,c893ab9c-5861-4d58-9051-b70ab806333b,TXN986582776278,TSU,Transaction Services Unit,Medium,calm,email,TSU_A3,2025-11-28 09:37:56,2025-11-29 00:37:56,15.0,48.0,0.0,resolved,0,Kindly assist. I was charged ₦12736.72 but the...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34293,CMP-034294,7127f873-a17c-4e6c-a07c-005720790db2,4e22c222-45e3-4920-a48f-6d65426f3a11,893e0f2b-aa71-4c3e-9200-6cd66aab363b,TXN410632645014,TSU,Transaction Services Unit,Medium,calm,email,TSU_A4,2025-07-20 16:16:09,2025-07-21 15:16:09,23.0,48.0,0.0,open,0,Kindly assist. This transaction with reference...
34294,CMP-034295,7127f873-a17c-4e6c-a07c-005720790db2,4e22c222-45e3-4920-a48f-6d65426f3a11,adf0fb18-39bf-4d37-98c2-5ef8eb75ec0e,TXN641534556410,TSU,Transaction Services Unit,Medium,angry,branch,TSU_A1,2024-10-21 12:54:22,2024-10-25 03:54:22,87.0,48.0,1.0,escalated,0,This is unacceptable. This transaction with re...
34295,CMP-034296,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,7a72cf43-245e-4bf6-899d-bce2c20cd2c3,TXN192966407617,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A3,2025-06-12 08:33:20,2025-06-12 20:33:20,12.0,48.0,0.0,resolved,0,I was charged ₦87113.04 but the transaction fa...
34296,CMP-034297,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,a3b9350e-41f3-47ac-ad84-4e6f5ad3b2a3,TXN214694088616,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A2,2025-09-12 14:55:41,2025-09-15 09:55:41,67.0,48.0,1.0,open,0,This transaction with reference TXN21469408861...
34297,CMP-034298,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,36466e7a-6ec7-4cf8-816e-b722db85785e,TXN512485966600,TSU,Transaction Services Unit,Medium,calm,email,TSU_A2,2025-10-18 13:08:35,2025-10-20 14:08:35,49.0,48.0,1.0,escalated,0,Kindly assist. This transaction with reference...

In [8]:
transaction_ids = transactions["transaction_id"]

In [9]:
complaints["customer_id"]

0        1721dbca-76cc-4f90-9f8e-46d7f0957162
1        1721dbca-76cc-4f90-9f8e-46d7f0957162
2        1721dbca-76cc-4f90-9f8e-46d7f0957162
3        1721dbca-76cc-4f90-9f8e-46d7f0957162
4        1721dbca-76cc-4f90-9f8e-46d7f0957162
                         ...
34294    7127f873-a17c-4e6c-a07c-005720790db2
34295    7127f873-a17c-4e6c-a07c-005720790db2
34296    7127f873-a17c-4e6c-a07c-005720790db2
34297    7127f873-a17c-4e6c-a07c-005720790db2
34298                         CUST-CC6026D394
Name: customer_id, Length: 34299, dtype: str

In [10]:
complaints

,complaint_id,customer_id,account_id,linked_transaction_id,linked_reference,department_code,department_name,priority_level,sentiment,complaint_channel,assigned_agent_id,complaint_timestamp,resolution_timestamp,resolution_time_hours,sla_hours_limit,sla_breach_flag,complaint_status,fraud_related,complaint_text
0,CMP-000001,1721dbca-76cc-4f90-9f8e-46d7f0957162,fa0065d6-188a-41f6-992b-0f9ad10d2e62,2cd76ff1-fad3-4840-bf75-cdfff1e91bdc,TXN550683510360,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A2,2025-08-24 07:42:31,2025-08-26 05:42:31,46.0,48.0,0.0,resolved,0,My transfer of ₦15204.51 with reference TXN550...
1,CMP-000002,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,6e420c2a-9f4c-4e3a-bba2-6950d66bc3ef,TXN682399898141,COC,Card Operations Center,High,calm,call_center,COC_A2,2025-10-04 01:29:08,2025-10-07 23:29:08,94.0,48.0,1.0,open,0,Kindly assist. The ATM transaction of ₦59396.0...
2,CMP-000003,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4d10db2d-f649-4c1a-b098-7ce1735cc4e5,TXN913375010250,COC,Card Operations Center,High,calm,mobile_app,COC_A2,2025-11-04 21:27:41,2025-11-08 05:27:41,80.0,48.0,1.0,escalated,0,Kindly assist. The ATM transaction of ₦49170.0...
3,CMP-000004,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4baabee9-6397-4a62-a1ae-f273da7a1391,TXN309153098109,FRM,Fraud Risk Management,Critical,angry,mobile_app,FRM_A3,2025-10-31 23:29:19,2025-11-01 14:29:19,15.0,24.0,0.0,escalated,1,This is unacceptable. I noticed an unauthorize...
4,CMP-000005,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,c893ab9c-5861-4d58-9051-b70ab806333b,TXN986582776278,TSU,Transaction Services Unit,Medium,calm,email,TSU_A3,2025-11-28 09:37:56,2025-11-29 00:37:56,15.0,48.0,0.0,resolved,0,Kindly assist. I was charged ₦12736.72 but the...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,CMP-034295,7127f873-a17c-4e6c-a07c-005720790db2,4e22c222-45e3-4920-a48f-6d65426f3a11,adf0fb18-39bf-4d37-98c2-5ef8eb75ec0e,TXN641534556410,TSU,Transaction Services Unit,Medium,angry,branch,TSU_A1,2024-10-21 12:54:22,2024-10-25 03:54:22,87.0,48.0,1.0,escalated,0,This is unacceptable. This transaction with re...
34295,CMP-034296,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,7a72cf43-245e-4bf6-899d-bce2c20cd2c3,TXN192966407617,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A3,2025-06-12 08:33:20,2025-06-12 20:33:20,12.0,48.0,0.0,resolved,0,I was charged ₦87113.04 but the transaction fa...
34296,CMP-034297,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,a3b9350e-41f3-47ac-ad84-4e6f5ad3b2a3,TXN214694088616,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A2,2025-09-12 14:55:41,2025-09-15 09:55:41,67.0,48.0,1.0,open,0,This transaction with reference TXN21469408861...
34297,CMP-034298,7127f873-a17c-4e6c-a07c-005720790db2,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,36466e7a-6ec7-4cf8-816e-b722db85785e,TXN512485966600,TSU,Transaction Services Unit,Medium,calm,email,TSU_A2,2025-10-18 13:08:35,2025-10-20 14:08:35,49.0,48.0,1.0,escalated,0,Kindly assist. This transaction with reference...
34298,CMP-56C1C84299,CUST-CC6026D394,ACCT-D0E313B167,NaN,NaN,NaN,Pending AI Routing,NaN,NaN,mobile,NaN,2026-03-06 12:21:35,NaN,NaN,NaN,NaN,open,0,I misplaced my atm card yesterday

In [11]:
complaints.head()

,complaint_id,customer_id,account_id,linked_transaction_id,linked_reference,department_code,department_name,priority_level,sentiment,complaint_channel,assigned_agent_id,complaint_timestamp,resolution_timestamp,resolution_time_hours,sla_hours_limit,sla_breach_flag,complaint_status,fraud_related,complaint_text
0,CMP-000001,1721dbca-76cc-4f90-9f8e-46d7f0957162,fa0065d6-188a-41f6-992b-0f9ad10d2e62,2cd76ff1-fad3-4840-bf75-cdfff1e91bdc,TXN550683510360,TSU,Transaction Services Unit,Medium,neutral,branch,TSU_A2,2025-08-24 07:42:31,2025-08-26 05:42:31,46.0,48.0,0.0,resolved,0,My transfer of ₦15204.51 with reference TXN550...
1,CMP-000002,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,6e420c2a-9f4c-4e3a-bba2-6950d66bc3ef,TXN682399898141,COC,Card Operations Center,High,calm,call_center,COC_A2,2025-10-04 01:29:08,2025-10-07 23:29:08,94.0,48.0,1.0,open,0,Kindly assist. The ATM transaction of ₦59396.0...
2,CMP-000003,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4d10db2d-f649-4c1a-b098-7ce1735cc4e5,TXN913375010250,COC,Card Operations Center,High,calm,mobile_app,COC_A2,2025-11-04 21:27:41,2025-11-08 05:27:41,80.0,48.0,1.0,escalated,0,Kindly assist. The ATM transaction of ₦49170.0...
3,CMP-000004,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,4baabee9-6397-4a62-a1ae-f273da7a1391,TXN309153098109,FRM,Fraud Risk Management,Critical,angry,mobile_app,FRM_A3,2025-10-31 23:29:19,2025-11-01 14:29:19,15.0,24.0,0.0,escalated,1,This is unacceptable. I noticed an unauthorize...
4,CMP-000005,1721dbca-76cc-4f90-9f8e-46d7f0957162,b1b43b1a-5cae-4871-a42a-7797cf814cfc,c893ab9c-5861-4d58-9051-b70ab806333b,TXN986582776278,TSU,Transaction Services Unit,Medium,calm,email,TSU_A3,2025-11-28 09:37:56,2025-11-29 00:37:56,15.0,48.0,0.0,resolved,0,Kindly assist. I was charged ₦12736.72 but the...

In [12]:
complaints["sentiment"].value_counts()

sentiment
neutral    12644
angry      12124
calm        9530
Name: count, dtype: int64

In [13]:
accounts.info()

<class 'pandas.DataFrame'>
RangeIndex: 7213 entries, 0 to 7212
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       7213 non-null   str
 1   customer_id      7213 non-null   str
 2   account_number   7213 non-null   int64
 3   account_type     7213 non-null   str
 4   currency         7213 non-null   str
 5   current_balance  7213 non-null   float64
 6   opened_date      7213 non-null   str
dtypes: float64(1), int64(1), str(5)
memory usage: 394.6 KB

In [14]:
accounts["account_type"].value_counts()

account_type
savings    3000
current    3000
solo       1213
Name: count, dtype: int64

In [15]:
customers["gender"]

0       female
1       female
2       female
3       female
4       female
         ...
2996      male
2997      male
2998    female
2999      male
3000      Male
Name: gender, Length: 3001, dtype: str

In [16]:
transactions

,transaction_id,transaction_reference_number,account_id,customer_id,channel,device_id,counterparty_bank,narration,transaction_type,amount,...,transaction_status,failure_reason,is_fraud_score,fraud_explainability_trace,merchant_category,merchant_name,salary_detected,Loan_signal_score,recommended_product,transaction_timestamp
0,77829fe4-2fcd-488b-8b48-8d5ce52898d4,TXN665294075747,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,atm,NaN,Premium Trust Bank,Fly get work walk sound.,credit,15300.71,...,successful,none,0.0,normal_pattern,telecoms,Glo,False,0.74,Investment Plan,2026-02-19 05:25:33
1,c8c36dca-e95b-4757-ae0f-bc2ac2b74d5f,TXN579796578227,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,pos,NaN,Polaris Bank,Right fight traditional white democratic.,debit,5924.62,...,successful,none,0.0,normal_pattern,restaurants,Cold Stone,False,0.87,Investment Plan,2025-12-01 22:43:14
2,6358eefd-f7fe-4b81-a4cd-cd651a197350,TXN477281106903,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,nibss_transfer,NaN,GTBank,Method option economic more plant large.,debit,9261.83,...,successful,none,0.0,normal_pattern,utilities,GOtv,False,0.87,Investment Plan,2026-01-12 13:19:06
3,8385a170-146e-459f-b652-f87621f23f51,TXN301358169925,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,nibss_transfer,NaN,Kuda,Person television attention these increase.,debit,40318.61,...,successful,none,0.0,normal_pattern,education,WAEC,False,0.72,Investment Plan,2025-06-28 09:07:23
4,5cb986ee-c06a-4274-8211-9a0131dc770f,TXN698516962758,fa0065d6-188a-41f6-992b-0f9ad10d2e62,1721dbca-76cc-4f90-9f8e-46d7f0957162,mobile_app,DEV-299DF744280D,Wema Bank,Step section it throughout together.,credit,40504.51,...,successful,none,0.0,normal_pattern,transport,Uber,False,0.75,Investment Plan,2026-01-06 12:50:43
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
216013,ffc337f6-8f22-4fbb-809b-5bd43a59e608,TXN811873598528,96c3b8e3-41e9-4ce2-8b2e-536b371ea824,7127f873-a17c-4e6c-a07c-005720790db2,atm,NaN,GTBank,Science campaign loss care responsibility read.,credit,52915.09,...,reversed,none,0.0,normal_pattern,utilities,DSTV,False,0.88,Personal Loan,2025-12-18 18:47:26
216014,TXN-133C84BF4F,ACCT-D0E313B167,REF-A65DFD5BE5,2026-03-06 12:33:05,10000.0,pending,NGN,credit,NaN,mobile,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216015,TXN-59A3B4E8F2,ACCT-D0E313B167,REF-16B8A17EC4,2026-03-06 12:37:04,5000.0,pending,NGN,debit,NaN,mobile,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216016,TXN-8ADC753909,ACCT-D0E313B167,REF-CFE54C9E94,2026-03-06 12:47:36,5000.0,pending,NGN,debit,NaN,mobile,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
216017,TXN-18BFE8AC3E,ACCT-D0E313B167,REF-14B2D316F9,2026-03-06 12:51:04,5000.0,pending,NGN,credit,NaN,NaN,...,NaN,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN